### ISSUE TITLE
Map TermsOfDelivery from CML to SalesOrder

### ISSUE THREAD

**Issue by nczeranka** [OpusCapita/sirius#25]
Subticket of OpusCapita/sales-invoice/issues/103

---

Via OpusCapita/sales-order/issues/26 new fields for the TermsOfDelivery 
- termsOfPaymentDays
- termsOfPaymentDiscountPerc1
- termsOfPaymentDiscountDays1

are added.

The CML provides only a TermsOfDeliveryId, like:
```
      <TermsOfDelivery id="delivery"/>
```
Hard code a mapping of 
- "delivery": termsOfPaymentDays =  5
- "T0": termsOfPaymentDays =  60
- "T1": termsOfPaymentDays =  30
- "T2": termsOfPaymentDays =  20

**Comment by John1s** [comment]
The service is now including the terms of delivery
