### ISSUE TITLE
Evaluate cross tenant role assignments

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/sirius#66]
User need to be able to initiate transactions for any tenants that said user has permission to do so on.
Example
User  admin_us@acmemax.com
Customer acme_us

User has customer-admin role for acmemax/* (which means for acme_us, but also for acme_de and acme_fi)

User would have Permission on sirius/upload-purchase-order via customer-admin role

Now in sirius, for this user it would be allowed to call transactions endpoint for any of these tenantIds:
```
/sirius/api/transactions/c_acme_us/purchase-order/created
/sirius/api/transactions/c_acme_de/purchase-order/created
/sirius/api/transactions/c_acme_fi/purchase-order/created
```

**Comment by John1s** [comment]
This is completed and available in production.
